/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _Migration {
  step: number;
}

export interface Armies {
  banner: string;
  createdBy: number;
  createdTime: Generated<Date | null>;
  id: Generated<number>;
  name: string;
  townHall: number;
  updatedTime: Generated<Date | null>;
}

export interface ArmyComments {
  armyId: number;
  comment: Generated<string | null>;
  createdBy: number;
  createdTime: Generated<Date | null>;
  id: Generated<number>;
  replyTo: Generated<number | null>;
  updatedTime: Generated<Date | null>;
}

export interface ArmyEquipment {
  armyId: number;
  equipmentId: number;
  id: Generated<number>;
}

export interface ArmyGuides {
  armyId: number;
  createdTime: Generated<Date | null>;
  id: Generated<number>;
  textContent: Generated<string | null>;
  updatedTime: Generated<Date | null>;
  youtubeUrl: Generated<string | null>;
}

export interface ArmyMetricEvents {
  armyMetricId: number;
  id: Generated<number>;
  lastSeen: Generated<Date | null>;
  visitorUUID: string;
}

export interface ArmyMetrics {
  armyId: number;
  id: Generated<number>;
  name: string;
  value: Generated<number>;
}

export interface ArmyNotifications {
  armyId: number;
  commentId: Generated<number | null>;
  id: Generated<number>;
  recipientId: number;
  seen: Generated<Date | null>;
  timestamp: Generated<Date>;
  triggeringUserId: Generated<number | null>;
  type: string;
}

export interface ArmyPets {
  armyId: number;
  hero: string;
  id: Generated<number>;
  petId: number;
}

export interface ArmyTags {
  armyId: number;
  tag: string;
}

export interface ArmyUnits {
  amount: number;
  armyId: number;
  home: Generated<string>;
  id: Generated<number>;
  unitId: number;
}

export interface ArmyVotes {
  armyId: number;
  createdTime: Generated<Date | null>;
  updatedTime: Generated<Date | null>;
  vote: number;
  votedBy: number;
}

export interface Equipment {
  clashId: number;
  epic: Generated<number>;
  hero: string;
  id: Generated<number>;
  name: string;
  order: Generated<number>;
}

export interface EquipmentLevels {
  blacksmithLevel: Generated<number | null>;
  equipmentId: number;
  id: Generated<number>;
  level: number;
}

export interface GameDataSync {
  appliedAt: Generated<Date | null>;
  hash: string;
  id: Generated<number>;
}

export interface Heroes {
  clashId: number;
  name: string;
  order: Generated<number>;
}

export interface Metrics {
  minAgeHours: number;
  name: string;
  weight: Generated<number>;
}

export interface PetLevels {
  id: Generated<number>;
  level: number;
  petHouseLevel: Generated<number | null>;
  petId: number;
}

export interface Pets {
  clashId: number;
  id: Generated<number>;
  name: string;
  order: Generated<number>;
}

export interface SavedArmies {
  armyId: number;
  id: Generated<number>;
  userId: number;
}

export interface Sessions {
  createdAt: Generated<Date>;
  id: string;
  lastVerifiedAt: Generated<Date>;
  secretHash: string;
  userId: number;
}

export interface TownHallHeroesMax {
  heroName: string;
  maxLevel: number;
  townHall: number;
}

export interface TownHalls {
  ccLaboratoryCap: Generated<number | null>;
  ccSiegeCapacity: Generated<number | null>;
  ccSpellCapacity: Generated<number | null>;
  ccTroopCapacity: Generated<number | null>;
  level: number;
  maxBarracks: Generated<number | null>;
  maxBlacksmith: Generated<number | null>;
  maxCc: Generated<number | null>;
  maxDarkBarracks: Generated<number | null>;
  maxDarkSpellFactory: Generated<number | null>;
  maxLaboratory: Generated<number | null>;
  maxPetHouse: Generated<number | null>;
  maxSpellFactory: Generated<number | null>;
  maxWorkshop: Generated<number | null>;
  siegeCapacity: Generated<number | null>;
  spellCapacity: Generated<number | null>;
  troopCapacity: Generated<number | null>;
}

export interface UnitLevels {
  buildingLevel: Generated<number | null>;
  id: Generated<number>;
  laboratoryLevel: Generated<number | null>;
  level: number;
  unitId: number;
}

export interface Units {
  airTargets: Generated<number>;
  clashId: number;
  groundTargets: Generated<number>;
  housingSpace: number;
  id: Generated<number>;
  isFlying: Generated<number>;
  isJumper: Generated<number>;
  isSuper: Generated<number>;
  name: string;
  order: Generated<number>;
  productionBuilding: string;
  type: string;
}

export interface UserRoles {
  role: string;
  userId: number;
}

export interface Users {
  createdTime: Generated<Date | null>;
  googleEmail: Generated<string | null>;
  googleId: string;
  id: Generated<number>;
  playerTag: Generated<string | null>;
  username: string;
}

export interface DB {
  __migration__: _Migration;
  armies: Armies;
  army_comments: ArmyComments;
  army_equipment: ArmyEquipment;
  army_guides: ArmyGuides;
  army_metric_events: ArmyMetricEvents;
  army_metrics: ArmyMetrics;
  army_notifications: ArmyNotifications;
  army_pets: ArmyPets;
  army_tags: ArmyTags;
  army_units: ArmyUnits;
  army_votes: ArmyVotes;
  equipment: Equipment;
  equipment_levels: EquipmentLevels;
  game_data_sync: GameDataSync;
  heroes: Heroes;
  metrics: Metrics;
  pet_levels: PetLevels;
  pets: Pets;
  saved_armies: SavedArmies;
  sessions: Sessions;
  town_hall_heroes_max: TownHallHeroesMax;
  town_halls: TownHalls;
  unit_levels: UnitLevels;
  units: Units;
  user_roles: UserRoles;
  users: Users;
}
