import type { Component, ComponentProps } from 'svelte';
import type { HTTPApi } from '$shared/http';
import { BANNERS, VALID_UNIT_HOME } from '$shared/utils';

export type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;

export type ModalAddons = {
	close(rtn?: unknown): void;
};
export type Modal<C extends Component<any> = Component<any>> = {
	/** An ID is autogenerated when calling `openModal` */
	id: number;
	/**
	 * The component that is rendered.
	 * This component should be wrapped in <C.Modal> ... </C.Modal>
	 */
	component: C;
	/**
	 * Props passed to the component.
	 * A `close` function prop is also always given for a way to close the modal.
	 * If the modal was opened using `openModalAsync`, the value passed to `close` will be the resolved value of the promise.
	 */
	props: ComponentProps<C> & ModalAddons;
};

export type ToastNotification = {
	/** An ID is autogenerated when calling `notify` */
	id: number;
	opts: {
		/** Notification title */
		title: string;
		/** Notification description */
		description: string;
		/** Notification theme @default 'primary' */
		theme?: 'primary' | 'success' | 'failure';
		/** How long the notification will show for (in ms) @default 1000ms */
		duration?: number;
	};
	/** Function that dismisses the notification */
	dismiss(): void;
};

export type ArmyNotification = {
	/** The ID of this notification in the database */
	id: number;
	/** When this notification was issued */
	timestamp: Date;
	/** The type of this notification */
	type: 'comment' | 'comment-reply';
	/** Whether this notification has been acknowledged */
	seen: boolean;
	/** Which army this notification corresponds to */
	armyId: number;
	armyName: string;
	/** The user to which this notification should go to - this is typically the army's creator */
	recipientId: number;
	recipientName: string;
	/** Info about who triggered this notification - could be the person who commented on the army */
	triggeringUserId: number | null;
	triggeringUserName: string | null;
	/** The ID of the comment this notification is relevant too */
	commentId: number | null;
};

export type User = {
	id: number;
	// Only included if user is requesting his own data
	googleId?: string;
	username: string;
	roles: string[];
	playerTag: string | null;
	level: number | null;
	createdTime: Date;
};

export type Session = {
	id: string;
	userId: number;
	lastVerifiedAt: Date;
	createdAt: Date;
};

export type TownHall = {
	level: number;
	/** Max barracks level at this town hall */
	maxBarracks: number;
	/** Max dark barracks level at this town hall - null means not unlocked yet. */
	maxDarkBarracks: number | null;
	/** Max laboratory level at this town hall - null means not unlocked yet. */
	maxLaboratory: number | null;
	/** Max spell factory level at this town hall - null means not unlocked yet. */
	maxSpellFactory: number | null;
	/** Max dark spell factory level at this town hall - null means not unlocked yet. */
	maxDarkSpellFactory: number | null;
	/** Max workshop level at this town hall - null means not unlocked yet. */
	maxWorkshop: number | null;
	/** Max clan castle level at this town hall - null means not unlocked yet. */
	maxCc: number | null;
	/** Max blacksmith level at this town hall - null means not unlocked yet. */
	maxBlacksmith: number | null;
	/** Max pet house level at this town hall - null means not unlocked yet. */
	maxPetHouse: number | null;
	/**
	 * Max level per hero at this town hall.
	 * At a lower town hall, this may be fully or partially empty (since some heroes may not be unlocked).
	 */
	heroMaxLevels: Partial<Record<string, number>>;
	/** Max available troops at this town hall (assuming max army camp). */
	troopCapacity: number;
	/** Max available spells at this town hall (assuming max spell factory). */
	spellCapacity: number;
	/** Max available siege machines at this town hall (assuming max workshop). */
	siegeCapacity: number;
	/** TODO: document */
	ccLaboratoryCap: number;
	/** Max available clan castle troops at this town hall (assuming max clan castle). */
	ccTroopCapacity: number;
	/** Max available clan castle spells at this town hall (assuming max clan castle). */
	ccSpellCapacity: number;
	/** Max available clan castle siege machines at this town hall (assuming max clan castle). */
	ccSiegeCapacity: number;
};

export type UnitType = 'Troop' | 'Siege' | 'Spell';
export type UnitHome = (typeof VALID_UNIT_HOME)[number];

export type Hero = {
	name: string;
	clashId: number;
	order: number;
};

export type BlackSmithLevel = {
	id: number;
	level: number;
	maxCommon: number;
	maxEpic: number;
};
export type UnitLevel = {
	id: number;
	unitId: number;
	level: number;
	/**
	 * Min production building level required to unlock this unit level.
	 * Building is determined by `Unit.productionBuilding` (Barrack, Spell Factory, Workshop, etc...).
	 * A null value means this level is not gated by a production building.
	 */
	buildingLevel: number | null;
	/**
	 * Min laboratory level required to upgrade to this unit level.
	 * A null value generally means level 1 (auto-unlocked when the unit itself is unlocked).
	 */
	laboratoryLevel: number | null;
};
export type EquipmentLevel = {
	equipmentId: number;
	level: number;
	/**
	 * Min blacksmith required to unlock this equipment level.
	 * A null value means no specific blacksmith level required.
	 */
	blacksmithLevel: number | null;
};
export type PetLevel = {
	id: number;
	petId: number;
	level: number;
	/**
	 * Min pet house level required to unlock this pet level.
	 * A null value means no specific pet house level required.
	 */
	petHouseLevel: number | null;
};

export type Unit = {
	/** ID of the unit in the `units` table */
	id: number;
	type: UnitType;
	name: string;
	clashId: number;
	order: number;
	housingSpace: number;
	/**
	 * Which building produces this unit (e.g. Barrack, Spell Factory, etc...).
	 */
	productionBuilding: string;
	/**
	 * True for super troop variants (e.g. Super Barbarian).
	 * Max level mirrors the regular variant.
	 */
	isSuper: boolean;
	isFlying: boolean;
	isJumper: boolean;
	airTargets: boolean;
	groundTargets: boolean;
	levels: UnitLevel[];
};
export type Equipment = {
	/** ID of the hero equipment in the `equipment` table */
	id: number;
	/** Which hero this equipment can be applied to */
	hero: string;
	name: string;
	clashId: number;
	order: number;
	/** True for epic-tier equipment. */
	epic: boolean;
	levels: EquipmentLevel[];
};
export type Pet = {
	/** ID of the pet in the `pets` table */
	id: number;
	name: string;
	clashId: number;
	order: number;
	levels: PetLevel[];
};
export type Guide = {
	/** ID of the guide in the `army_guides` table */
	id: number;
	armyId: number;
	textContent: string | null;
	youtubeUrl: string | null;
	createdTime: Date;
	updatedTime: Date;
};

export type StaticGameData = {
	units: Unit[];
	townHalls: TownHall[];
	equipment: Equipment[];
	pets: Pet[];
	heroes: Hero[];
};

type UserUtils = {
	/**
	 * Returns true if user has every role specified.
	 */
	hasRoles: (...roles: string[]) => boolean;
	notifications: ArmyNotification[];
};

export type AppState = {
	http: HTTPApi;
	// Frequently used data (cache)
	units: Unit[];
	townHalls: TownHall[];
	heroes: Hero[];
	heroNames: string[];
	equipment: Equipment[];
	pets: Pet[];
	user: (User & UserUtils) | null;
	// Modals
	modals: Modal[];
	openModal<T = unknown, C extends Component<any> = Component<any>>(
		component: C,
		props?: Omit<ComponentProps<C>, keyof ModalAddons>,
		onClose?: (rtnValue?: T) => void
	): void;
	openModalAsync<T = unknown, C extends Component<any> = Component<any>>(
		component: C,
		props?: Omit<ComponentProps<C>, keyof ModalAddons>
	): Promise<T | undefined>;
	// Notifications
	notifications: ToastNotification[];
	notify(opts: ToastNotification['opts']): void;
	// Confirm
	confirm(confirmText: string): Promise<boolean>;
	/**
	 * Navigates to auth login endpoint.
	 * Ensures it redirects back to current page with the current scroll position.
	 */
	requireAuth(): Promise<void>;
};

export type Banner = (typeof BANNERS)[number];
