name: build-image
on:
  push:
    # Any version tag like v0.8.0, v0.8.1, etc...
    tags: ['v*']
  # Allow manual trigger from GH UI
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Strips `v` prefix for image tag, e.g. v0.8.0 -> 0.8.0
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ninjainshade/clash-armies
          tags: type=semver,pattern={{version}}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
